### ISSUE TITLE
Ideas for improvement

### ISSUE THREAD

**Issue by swapdisk** [oxidecomputer/oxide-and-friends#114]
First, let me say I'm a big fan and also love how you've open sourced the show notes. I have a couple suggestions for the community here to consider. If we agree these are good, I'm happy to do the work and raise a PR... 

1. Would it make sense to add a Creative Commons license? Maybe [CC-BY](https://creativecommons.org/licenses/by/4.0/)?
2. Some of the "cover art" images are really fun. For example, my favorite is this one [here](https://twitter.com/ahl/status/1682058621402894337). What do you think about including these images on the respective show notes pages?

**Comment by ahl** [comment]
> 1. Would it make sense to add a Creative Commons license? Maybe [CC-BY](https://creativecommons.org/licenses/by/4.0/)?

Sounds good. Would you be interested in a PR?

> 2. Some of the "cover art" images are really fun. For example, my favorite is this one [here](https://twitter.com/ahl/status/1682058621402894337). What do you think about including these images on the respective show notes pages?

I'm loath to add more labor, minimal as it is. The images **are** available by downloading the YouTube video... does that suffice?

**Comment by swapdisk** [comment]
> Sounds good. Would you be interested in a PR?

Yes, I'll open a PR. 

> I'm loath to add more labor, minimal as it is. The images **are** available by downloading the YouTube video... does that suffice?

That's fine.
