### ISSUE TITLE
I'm missing a link in last episode's notes

### ISSUE THREAD

**Issue by felix91gr** [oxidecomputer/oxide-and-friends#147]
Here's the current show notes for it:

https://github.com/oxidecomputer/oxide-and-friends/blob/master/2024_09_23.md

However at around the 53:50 timestamp in the YT video (https://m.youtube.com/watch?v=Y-cC5pUXjbQ), one of Nathaniel's posts about remote hardware work is mentioned. And that link isn't present in the notes. I'd love to read it; could you please add a link in the notes? :)

**Comment by ahl** [comment]
done; thanks

**Comment by felix91gr** [comment]
No problem. Thank you! 😊
